### ISSUE TITLE
Check flow enabled files only

### ISSUE THREAD

**Issue by hardtack** [lbolla/emacs-flycheck-flow#22] opened 2017-02-12 06:29 UTC
Since `javascript-flow` checker uses `flow check-contents`, It always check flow type even if `@flow` header not exists.
The checker should ignore files not exist in result of `flow ls`.

I tried to used following as predicate function
``` emacs lisp
(defun flycheck-flow--predicate ()
  "Alternative flycheck predication."
  (and
   buffer-file-name
   (file-exists-p buffer-file-name)
   (locate-dominating-file buffer-file-name ".flowconfig")
   (let* ((flow (flycheck-checker-executable 'javascript-flow))
          (lines (process-lines flow "ls")))
     (member (file-truename buffer-file-name) lines)))))
```

But it's too slow to be used for predicate function (cause it calls shell command)

**Comment by hardtack** [comment] 2017-02-12 06:49
Additionally, I added `(flycheck-buffer-saved-p)` to the head of `(and)` conditions to check file when saved only.
But it would be better if we can check dynamically without saving.

**Comment by lbolla** [comment] 2017-02-14 16:03
This is a duplicate of https://github.com/lbolla/emacs-flycheck-flow/issues/18

**Closed as completed** 2017-02-14 16:03 UTC
